name: SQLMap and Django Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.10' ]

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Basic SQLMap test
      - name: Basic Import Test
        run: python -c "import sqlmap; import sqlmapapi"

      # Run Django tests
      - name: Django Tests
        run: python manage.py test
